#.travis.yml
sudo: required
dist: trusty
language: node_js
node_js:
  - "8.0.0"

branches:
  only:
    - dev

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run test
  - npm build

notifications:
  email:
    on_failure: change
    on_success: change