#.travis.yml
sudo: required
dist: trusty
language: node_js
node_js:
  - "8.0.0"

branches:
  only:
    - dev

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - npm install
script:
  - npm build
  - npm run test

notifications:
  email:
    on_failure: change
    on_success: change