#.travis.yml
sudo: required 
dist: trusty
language: node_js
node_js:
  - "node"

branches:
  only:
    - dev
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# to run components unit tests with chrome
before_install:
  - export CHROME_BIN=chromium-browser
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install
  - npm install -g npx

script:
  #- npx nuxt build
  - node_modules/.bin/nuxt build
  - npx karma start test/unit/karma.conf.js

notifications:
  email:
    on_failure: change
    on_success: change
